#!/bin/bash
HERE="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck disable=SC1091
source "${HERE}/mfxenv"

if [ "$1" == "optimize" ]; then
    # Launch with only the optimize devices and functions (xopt, blop)
    shift
    "${HERE}/mfx/optimize/real_interactive.sh" "$@"
else
    # Launch hutch-python with all devices and functions
    hutch-python --cfg "${HERE}/conf.yml" "$@"
fi
