#!/bin/bash


# if [ "$#" -ne 1 ]; then
#     printf "\n Please provide camera PV. Example: focus_scan MFX:GIGE:05\n\n"
#     exit 1
# fi

printf "\n [*] Sourcing PCDS Conda...   "
    source /reg/g/pcds/pyps/conda/py36env.sh > /dev/null
printf "done. \n"

printf " [*] Initializing script...   "
    python /reg/g/pcds/pyps/apps/hutch-python/mfx/scripts/focus_scan.py "$@"
