name: MkDocs Build
on:
  push:
    branches:
      - documentation
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install mkdocs mkdocs-material mkdocstrings "mkdocstrings[python]"
      - run: mkdocs gh-deploy --force
